name: Build

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42
  test:
    uses: mackerelio/workflows/.github/workflows/go-test.yml@main
