name: Build

on:
  push:
    branches:
    - master
  pull_request:
env:
  GO111MODULE: on
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
  test:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macOS-10.15', 'windows-2019']
        go: ['1.15.x', '1.14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make cover
    - uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-profile: .profile.cov
        parallel: true
        job-number: ${{ strategy.job-index }}
  finish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
